---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: eduardoarndt/file-sharing-platform-backend
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: "backend-db-mongodb.default.svc.cluster.local"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: "root"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-mongodb
                  key: mongodb-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
